# fly.toml app configuration file generated for micropost1 on 2023-12-08T05:27:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "micropost1"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
